version: "3.1"

services:
  web:
    image: nginx:alpine
    container_name: godash-docs
    restart: always
    volumes:
      - ./docs_html:/usr/share/nginx/html
      - ./docs_images:/usr/share/nginx/html/images
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
