name: CD

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: [ self-hosted, main ]

    steps:
      - uses: actions/checkout@v3

      - name: Deployment
        run: |
          docuowl --input docs --output docs_html \
          && docker compose down \
          && docker compose up -d